### ISSUE TITLE
How to generate "build/svg/icons.svg": "build/svg/icons.05c988844bf3b74a.svg" in manifest.json?

### ISSUE THREAD

**Issue by insekticid** [cascornelissen/svg-spritemap-webpack-plugin#149] opened 2021-01-29 09:38 UTC
What I am doing wrong? Thanks for help!

```
new SVGSpritemapPlugin([
    'assets/svg/**/*.svg',
], {output: {filename: 'svg/icons.[contenthash].svg'}, sprite: { prefix: false, generate: {title: false } }})
```

**Comment by cascornelissen** [comment] 2021-01-29 16:11
I'm going to need a bit more information 😅  What is it you're trying to do exactly, what have you tried and what isn't working as you expected?

I'm guessing you also use `webpack-manifest-plugin` to generate a `manifest.json` but it doesn't include the spritemap SVG? If that's the case, can you provide a minimal repository that I can use to reproduce the issue?

**Comment by toooni** [comment] 2021-02-02 17:29
I am not sure but I think I have the same issue:
```
When using a `contenthash` in the filename the entry in manifest.json looks like this:
 "/build/sprite.aeb090b754a85b4b.svg": "/build/sprite.aeb090b754a85b4b.svg",
```

the desired entry would be:
```
 "/build/sprite.svg": "/build/sprite.aeb090b754a85b4b.svg",
```

**Comment by toooni** [comment] 2021-02-03 13:27
I think I've worked it out. The new version starting at v3.0.0 from https://github.com/shellscape/webpack-manifest-plugin has a new `removeKeyHash` option. This option by default is `/([a-f0-9]{32}\.?)/gi`. This means that only hashes with the length of 32 characters are removed.

A working solution is to set the `removeKeyHash` option to `/([a-f0-9]{16,32}\.?)/gi`.

**Comment by cascornelissen** [comment] 2021-02-04 10:39
It looks like more plugins are running into this: https://github.com/shellscape/webpack-manifest-plugin/issues/241.

I'm hoping they change it on the side of `webpack-manifest-plugin` because I don't see any specific reasons why a hash has to be a certain length (in this scenario). Let's keep this issue (and the PR) open for now until things are clearer.

The workaround for now is to manually specify the `removeHashKey` option as described in https://github.com/cascornelissen/svg-spritemap-webpack-plugin/issues/149#issuecomment-772505150.

**Comment by cascornelissen** [comment] 2021-02-05 21:38
Submitted the PR to increase the range in `webpack-manifest-plugin` at https://github.com/shellscape/webpack-manifest-plugin/pull/248.

Also found out about the [`output.hashDigestLength` Webpack option](https://webpack.js.org/configuration/output/#outputhashdigestlength) so the change in ec05468 should increase consistency a bit in that regard.

**Comment by cascornelissen** [comment] 2021-02-16 09:33
Since https://github.com/shellscape/webpack-manifest-plugin/pull/248 has been merged and I'm expecting it to be released not too long from now as well, I'm going to close this issue. Thanks to everyone involved ✌🏼

**Closed by cascornelissen** 2021-02-16 09:33 UTC
Labels: bug
