### ISSUE TITLE
Can't find the output svg

### ISSUE THREAD

**Issue by maoqxxmm** [cascornelissen/svg-spritemap-webpack-plugin#24] opened 2018-04-05 03:06 UTC
Hey, I use create-react-app to start my project. And the webpack config is shown blow:
```
 output: {
    // Add /* filename */ comments to generated require()s in the output.
    pathinfo: true,
    // This does not produce a real file. It's just the virtual path that is
    // served by WebpackDevServer in development. This is the JS bundle
    // containing code from all our entry points, and the Webpack runtime.
    filename: 'static/js/bundle.js',
    // There are also additional JS chunk files if you use code splitting.
    chunkFilename: 'static/js/[name].chunk.js',
    // This is the URL that app is served from. We use "/" in development.
    publicPath: publicPath,
    // Point sourcemap entries to original disk location (format as URL on Windows)
    devtoolModuleFilenameTemplate: info =>
      path.resolve(info.absoluteResourcePath).replace(/\\/g, '/'),
  },
plugins: [
    // Makes some environment variables available in index.html.
    // The public URL is available as %PUBLIC_URL% in index.html, e.g.:
    // <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
    // In development, this will be an empty string.
    new InterpolateHtmlPlugin(env.raw),
    // Generates an `index.html` file with the <script> injected.
    new HtmlWebpackPlugin({
      inject: true,
      template: paths.appHtml,
    }),
    // Add module names to factory functions so they appear in browser profiler.
    new webpack.NamedModulesPlugin(),
    // Makes some environment variables available to the JS code, for example:
    // if (process.env.NODE_ENV === 'development') { ... }. See `./env.js`.
    new webpack.DefinePlugin(env.stringified),
    // This is necessary to emit hot updates (currently CSS only):
    new webpack.HotModuleReplacementPlugin(),
    // Watcher doesn't work well if you mistype casing in a path so we use
    // a plugin that prints an error when you attempt to do this.
    // See https://github.com/facebookincubator/create-react-app/issues/240
    new CaseSensitivePathsPlugin(),
    // If you require a missing module and then `npm install` it, you still have
    // to restart the development server for Webpack to discover it. This plugin
    // makes the discovery automatic so you don't have to restart.
    // See https://github.com/facebookincubator/create-react-app/issues/186
    new WatchMissingNodeModulesPlugin(paths.appNodeModules),
    // Moment.js is an extremely popular library that bundles large locale files
    // by default due to how Webpack interprets its code. This is a practical
    // solution that requires the user to opt into importing specific locales.
    // https://github.com/jmblog/how-to-optimize-momentjs-with-webpack
    // You can remove this if you don't use Moment.js:
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
    new SVGSpritemapPlugin(),
]
```
But when I use `npm start`, there is no spritemap.svg in my workspace. If I set `path` like `path.join(__dirname, '../src/')`,  there is no help either. I don't know what's wrong...

version: 1.1.1
webpack version: 3.8.1

**Comment by maoqxxmm** [comment] 2018-04-05 07:14
@cascornelissen I have set the `src` but nothing changes...
```
new SVGSpritemapPlugin({
  src: path.join(__dirname, '../src/assets/svg/*.svg')
})
```
There are 2 svg files in this folder. And I add a break point at 
```
 var generateSVG = function() {
    // No point in generating when there are no files
    if ( !files.length ) {
        return false;
    }
…………
```
And I get files.length equals 2, so I believe that it's not the problem of source...
Maybe it's because of the `output` option of webpack?

**Comment by cascornelissen** [comment] 2018-04-05 07:30
Hmm, interesting... Could you include your webpack output (stats) in this issue? Let's see it actually adds the chunk.

If you have the time a small reproducible repository might help me debug this as well 😉

**Comment by maoqxxmm** [comment] 2018-04-05 09:08
@cascornelissen hey, I have create a test repository: https://github.com/maoqxxmm/svg-test
Thanks for your help😊

**Comment by cascornelissen** [comment] 2018-04-05 09:48
Great! I'll check this evening (in about 6 hours in my timezone) and will let you know :v:

**Comment by cascornelissen** [comment] 2018-04-05 17:25
@maoqxxmm, I've just tested your setup and running `npm run build` (after adding the plugin to `config/webpack.config.prod.js` as well) results in a `spritemap.svg` in the build directory.

I'm not quite sure how the webpack-dev-server (used when running `npm run start`) setup for the `create-react-app` project is but I can't really help you with that. The plugin seems to be working fine, it finds the files and generates a spritemap.

**Comment by maoqxxmm** [comment] 2018-04-06 02:38
@cascornelissen Thanks for your help. Maybe I should ask webpack team about this 😭

**Comment by cascornelissen** [comment] 2018-04-07 14:05
@maoqxxmm, sorry I can't help you any further with this, asking the developers over at the webpack or create-react-app might get you somewhere. 

I would personally advice against using this plugin in combination with React by the way, inlining the SVGs with something like `react-inlinesvg` would probably be better.

I'm closing this for now, feel free to comment/open a new issue when you find anything that might imply it's an issue with the plugin.

**Closed by cascornelissen** 2018-04-07 14:05 UTC
